name: Tests Notify Discord

on: 
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '25 21 * * *' # all days at 18:00 
  workflow_dispatch:

jobs:
  cypress-tests:
    name: Executar Cypress e publicar relatório
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run
    
    - name: Generated HTML
      run: |
        npx mochawesome-merge mochawesome-report/*.json > mochawesome.json
        npx mochawesome-report-generator mochawesome.json -o mochawesome-html
    
    - name: Rename report to index.html
      run: mv mochawesome-html/mochawesome.html mochawesome-html/index.html

    - name: Deploy GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: mochawesome-html

    - name: Notify Discord on Success
      if: success()
      run: |
         curl -H "Content-Type: application/json" \
         -X POST \
         -d '{
            "embeds": [{
            "title": "✅ Pipeline de Testes - Sucesso",
            "description": "Os testes passaram com sucesso.",
            "color": 65280,
            "fields": [
              { "name": "Status", "value": "🟢 Sucesso", "inline": true },
              { "name": "Branch", "value": "${{ github.ref_name }}", "inline": true },
              { "name": "Autor", "value": "${{ github.actor }}", "inline": true },
              { "name": "📊 Relatório", "value": "[Clique aqui](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }})", "inline": false }
            ],
            "footer": { "text": "GitHub Actions | Cypress" },
            "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'"
            }]
         }' \
         ${{ secrets.DISCORD_WEBHOOK }}

    - name: Notify Discord on Failure
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{
        "embeds": [{
            "title": "❌ Pipeline de Testes - Falhou",
            "description": "Atenção! Algum teste falhou na execução.",
            "color": 16711680,
            "fields": [
            { "name": "Status", "value": "🔴 Falhou", "inline": true },
            { "name": "Branch", "value": "${{ github.ref_name }}", "inline": true },
            { "name": "Autor", "value": "${{ github.actor }}", "inline": true },
            { "name": "📊 Relatório", "value": "[Clique aqui](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }})", "inline": false }
            ],
            "footer": { "text": "GitHub Actions | Cypress" },
            "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'"
        }]
        }' \
        ${{ secrets.DISCORD_WEBHOOK }}